sonar.projectKey=Aak172003_mernspace-auth-service
sonar.organization=aak172003

sonar.projectName=mernspace-auth-service

sonar.sources=src
sonar.tests=tests

# Exclude all the files from static code analysis
sonar.exclusions=**/node_modules/**/* , **/dist/**/*, **/build/**/*, **/migration/**/*
# Wait for the quality gate to be passed
sonar.qualitygate.wait=true

# Path to the coverage file
sonar.javascript.lcov.reportPaths=./coverage/lcov.info

# Disable the SCM exclusions , which means it will reference the gitignore files  
sonar.scm.exclusions.disabled=true